### ISSUE TITLE
Breaking change in 1.2.0

### ISSUE THREAD

**Issue by naugtur** [parro-it/spawn-shell#6]
https://github.com/parro-it/spawn-shell/commit/eccf0c2e0fe23606d228e14fbe1ee77537d8fe73#diff-1dd241c4cd3fd1dd89c570cee98b79ddR31

This line seems to be breaking my usecase.
I'm running `npm install` via spawn-shell and the env is limited to everything but just the path, so:
- npm v2 has trouble runnning at all
- with npm v3 building native modules fail

Both with very criptic messages that don't help debugging, but the line above is the only change and 1.1.4 works.

It seems current env gets passed by default. What was the reason behind that line? Can it be optional?

**Comment by parro-it** [comment]
To what line exactly are you referring? In your linked diff, one line it's in a test, and the other is only a log...

If you are referring to line `opts.env.PATH = npmRunPath({path: opts.env.PATH});` it is used to inject in the path you node_modules/.bin directory.

> It seems current env gets passed by default. 

No, it isn't. It default to `{}`. You should pass `process.env` as `env` option if you would to use them. Maybe this is the cause of your problems?

**Comment by naugtur** [comment]
In that case, I don't know what happens. will investigate more.

Try using https://github.com/naugtur/secure-dependencies with v1.2.0 to reproduce.

**Comment by parro-it** [comment]
Just tried. It seems to work well both with version 1.2.0 and with 1.1.x.
It could be a problem with the specific project you are using to test?

Could you post the npm errors? Even if they are cryptic, maybe using 4 eyes we can discover something useful there...

**Comment by naugtur** [comment]
I run it on the example app inside the repo.

Go to the folder, npm i then npm start.
It fails to build heapdump.
With npm 2 it fails to run npm

**Comment by parro-it** [comment]
I was able to run it if I pass `process.env` as `env` parameter to `spawn-shell`:

```bash

....

npm WARN package.json exampleapp@1.0.0 No README data
>>>> cd /home/parroit/repos/secure-dependencies/exampleapp/secure-dependencies-bundle && npm dedupe
npm WARN unavoidable conflict debug { '/home/parroit/repos/secure-dependencies/exampleapp/secure-dependencies-bundle/node_modules/express/node_modules/debug': '2.6.1',
npm WARN unavoidable conflict   '/home/parroit/repos/secure-dependencies/exampleapp/secure-dependencies-bundle/node_modules/express/node_modules/finalhandler/node_modules/debug': '2.6.3',
npm WARN unavoidable conflict   '/home/parroit/repos/secure-dependencies/exampleapp/secure-dependencies-bundle/node_modules/ioredis/node_modules/debug': '2.6.3' }
npm WARN unavoidable conflict Not de-duplicating
mime-types@2.1.15 node_modules/express/node_modules/mime-types
└── mime-db@1.27.0
>>>> cd /home/parroit/repos/secure-dependencies/exampleapp/secure-dependencies-bundle && node /home/parroit/repos/secure-dependencies/node_modules/.bin/nsp check
(+) No known vulnerabilities found
Done. Here is your tarball:
/home/parroit/repos/secure-dependencies/exampleapp/exampleapp-1.0.0.tgz

~/repos/secure-dependencies/exampleapp master* 15s
❯ npm -v
2.14.4

```


 I wrote a PR with the change to your repo.
Since `process.env` seems a good a default for `env` option, I think I'll publish a new major release with that as default for env option instead the actual empty object.

**Comment by naugtur** [comment]
Thanks!

Sounds like a good default.
